### PR TITLE
Update ARMA.py

### PR DESCRIPTION
**Pull request by abdaghar**
No more ARMA in statsmodels package latest version

### CODE REVIEW

**Comment by AlexHuang2** [comment]
This is my current working solution (some modification may be needed to integrate in with the rest of the package's code seamlessly):

1) add `from statsmodels.tsa.arima.model import ARIMA` to the beginning (without removing `import statsmodels.tsa.api as sm`)
2) refactor `ARMA._getStartingVals()` to:
```
def _getStartingVals(self):
    if self._data is not None:
        if self._include_constant:
            c = 'c'
        else:
            c = 'nc'
        try:
            # statsmodels.tsa.arima_model.ARMA has been discontinued and replaced with statsmodels.tsa.arima.model.ARIMA, just force d=0 to make it an ARMA
            arma = ARIMA(self._data.values, order=(self._order['AR'],0,self._order['MA']), trend=c)
            model = arma.fit()
            # the original and now-deprecated statsmodels.tsa.arima_model.ARMA function does NOT include sigma2 in its params when returning the fitted results, so filter it out
            self._startingValues = [param for param,name in zip(model.params,arma.param_names) if name!='sigma2']
        except ValueError:
            self._startingValues = None            
    else:
        self._startingValues = np.zeros((self._pnum,))+0.5
```

References:
- https://www.statsmodels.org/devel/generated/statsmodels.tsa.arima.model.ARIMA.html
- https://www.statsmodels.org/devel/generated/statsmodels.tsa.arima.model.ARIMAResults.html#statsmodels.tsa.arima.model.ARIMAResults
- https://www.statsmodels.org/0.8.0/generated/statsmodels.tsa.arima_model.ARMAResults.html#statsmodels.tsa.arima_model.ARMAResults

**Review by AlexHuang2 — CHANGES_REQUESTED** [review]
There is some change in the structure of the new ARIMA function. Running the current solution results in `TypeError: fit() got an unexpected keyword argument 'trend'`. I've proposed a working solution [here](https://github.com/iankhr/armagarch/pull/6#issuecomment-1183838062).

**Comment by HuihanYang-Arya** [comment]
But in this case, in the `armagarch/gir.py`, variable `alpha` will be determined as (0,). Do you encounter this problem? I think the code need to be further modified.

**Comment by foxintohumanbeing** [comment]
Sorry for my previous wrongly described description. Now I will describe my problem in detail. I try to run the `examples/ftse_volatility.py`. It gives error at line 113 in `gir.py` ht = ht+etlagsp@alpha, And if you try to print all the related variables, you will find that the shape of `ht` is `(7041,)`, the shape of `etlagsp` is `(7041,2)` (here 2 is because of my parameter setting)  and  the shape of `alpha` is `(1,)`. 

For your more information, my python version is `3.9.12`, numpy version is `1.21.5` and pandas version is `2.0.1`. Below are the detailed error.

```<module>mdl.fit()File "/nfs-home/yanghuihan/anaconda3/Lib/python3.9/site-packages/armagarch/empModel.py", line 168，in fitself. imode，self. smodescipy.optimize.fmin ssqp(self.optApplyFile "/nfs-home/yanghuihan/anaconda3/Lib/python3.9/site-packages/scipy/optimize/_slsqp_py.py", line 213, in fmin _slsqpminimize slsqp(func，x0，args，jac=fprime，bounds=bounds,res :File "/nfs-home/yanghuihan/anaconda3/lib/python3.9/site-packages/scipy/optimize/ slsqp-py.py", line 381, in -minimize slsqpfunction(funcstpreparescalarjac=jac，args=args， epsilon=epsFile "/nfs-home/yanghuihan/anaconda3/lib/python3.9/site-packages/scipy/optimize/ optimize.py", line 332, in prepare scalar functiorsfScalarFunction(fun，x0，args,grad，hessFile "/nfs-home/yanghuihan/anaconda3/lib/python3.9/site-packages/scipy/optimize/ differentiable functions.py", line 158,in initself. update fun()File "/nfs-home/yanghuihan/anaconda3/ib/python3.9/site-packages/scipy/optimize/ differentiable functionspy", line 251, in _update furself. update fun impl()File“/nfs-home/yanghuihan/anaconda3/lib/python3.9/sitedifferentiable_functions.py"， line 155，in update_funself.f = fun wrapped(self.x)differentiable functions.py"，ine 137，in fun wrappedFile“/nfs-home/yanghuihan/anaconda3/lib/python3.9/sitefx = fun(np.copy(x)，*args)File"/nfs-home/vanghuihan/anaconda3/ ib/python3.9/site-packagespModel.py"，line 74，in optApplyvals = self.apply(paramsFile"/nfs-home/yanghuihan/anaconda3/lib/python3.9/site-packageh/empModel.py"，line 63，in applyht = self. vol.ht(parslil. dataFile "/nfs-home/yanghuihan/anaconda3/Lib/python3.9/site-packages/armagarch/gjr.py", line 113， in ht ht = ht+etlagsp@alpha ValueError: matmul: Input operandsignature(n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)```

**Comment by HuihanYang-Arya** [comment]
> > But in this case, in the `armagarch/gir.py`, variable `alpha` will be determined as (0,). Do you encounter this problem? I think the code need to be further modified.
> 
> can you please describe in more detail the problem you are talking about ?

Sorry for my previous wrongly described description. Now I will describe my problem in detail. I try to run the examples/ftse_volatility.py. It gives error at line 113 in gir.py ht = ht+etlagsp@alpha, And if you try to print all the related variables, you will find that the shape of ht is (7041,), the shape of etlagsp is (7041,2) (here 2 is because of my parameter setting) and the shape of alpha is (1,).

For your more information, my python version is 3.9.12, numpy version is 1.21.5 and pandas version is 2.0.1. Below are the detailed error.

<module>mdl.fit()File "/nfs-home/yanghuihan/anaconda3/Lib/python3.9/site-packages/armagarch/empModel.py", line 168，in fitself. imode，self. smodescipy.optimize.fmin ssqp(self.optApplyFile "/nfs-home/yanghuihan/anaconda3/Lib/python3.9/site-packages/scipy/optimize/_slsqp_py.py", line 213, in fmin _slsqpminimize slsqp(func，x0，args，jac=fprime，bounds=bounds,res :File "/nfs-home/yanghuihan/anaconda3/lib/python3.9/site-packages/scipy/optimize/ slsqp-py.py", line 381, in -minimize slsqpfunction(funcstpreparescalarjac=jac，args=args， epsilon=epsFile "/nfs-home/yanghuihan/anaconda3/lib/python3.9/site-packages/scipy/optimize/ optimize.py", line 332, in prepare scalar functiorsfScalarFunction(fun，x0，args,grad，hessFile "/nfs-home/yanghuihan/anaconda3/lib/python3.9/site-packages/scipy/optimize/ differentiable functions.py", line 158,in initself. update fun()File "/nfs-home/yanghuihan/anaconda3/ib/python3.9/site-packages/scipy/optimize/ differentiable functionspy", line 251, in _update furself. update fun impl()File“/nfs-home/yanghuihan/anaconda3/lib/python3.9/sitedifferentiable_functions.py"， line 155，in update_funself.f = fun wrapped(self.x)differentiable functions.py"，ine 137，in fun wrappedFile“/nfs-home/yanghuihan/anaconda3/lib/python3.9/sitefx = fun(np.copy(x)，*args)File"/nfs-home/vanghuihan/anaconda3/ ib/python3.9/site-packagespModel.py"，line 74，in optApplyvals = self.apply(paramsFile"/nfs-home/yanghuihan/anaconda3/lib/python3.9/site-packageh/empModel.py"，line 63，in applyht = self. vol.ht(parslil. dataFile "/nfs-home/yanghuihan/anaconda3/Lib/python3.9/site-packages/armagarch/gjr.py", line 113， in ht ht = ht+etlagsp@alpha ValueError: matmul: Input operandsignature(n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

**Review by iankhr — APPROVED** [review]

**Pull request merged**
